name: .NET

on: push

jobs:  
  windows-build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .Net Core SDK
      uses: actions/setup-dotnet@v1.8.2
      with: 
        dotnet-version: 6.0.100
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
